name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
      
      - name: Create build directory and copy build assets
        run: |
          mkdir -p build/icons
          # entitlementsファイルをコピー
          cp resources/build-assets/entitlements/entitlements.mac.plist build/
          cp resources/build-assets/entitlements/entitlements.mac.inherit.plist build/
          # アイコンファイルをコピー
          cp resources/build-assets/icons/icon.png build/icons/
          # パーミッションを設定
          chmod 644 build/entitlements.mac.plist
          chmod 644 build/entitlements.mac.inherit.plist
          chmod 644 build/icons/icon.png
          # ファイルの確認
          ls -la build/
          ls -la build/icons/
      
      - name: Import Code-Signing Certificates
        if: github.event_name != 'pull_request'
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
      
      - name: Build macOS DMG
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.MACOS_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      
      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: Blob-Uploader-${{ github.ref_name }}-mac
          path: dist/*.dmg
          retention-days: 5
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.dmg
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
